---
title: Lorem ipsum - lorme ipsm

description: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum

keywords: foo, bar

image: /uploads/intro.jpg
author: Lorem ipsum
seo:
  type: organisation
  name: Lorem
  
email: your-email@domain.com







timezone: UTC
collections:
  kultavilla:
    title: Kultavilla
    output: false
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: false
baseurl: "/Test"
url: 
markdown: kramdown
exclude:
- Gemfile
- Gemfile.lock
sass:
  style: compressed
gems:
  - jekyll-seo-tag